runtime: python27
api_version: 1
threadsafe: yes

handlers:

# Endpoints handler for API
- url: /_ah/api/.*
  script: main.api

# Endpoints handler for API
- url: /_ah/spi/.*
  script: main.api

# Folder for components
- url: /bower_components/(.+)
  static_files: app/components/\1
  upload: app/components/(.*)

# Photo upload routing
- url: /upload
  script: main.app

- url: /upload_photo
  script: main.app

- url: /img
  script: main.app

- url: /fullimg
  script: main.app

# Most Traffic
- url: /(.+)
  static_files: app/\1
  upload: app/(.*)

- url: /
  static_files: app/index.html
  upload: app/index.html

libraries:
- name: endpoints
  version: 1.0

- name: PIL
  version: 1.1.7

skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?
